// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xdEWySrazjDxNf91K5_Lxetfo-FuOAw',
    appId: '1:975258799788:web:05cf06390d86671e09d909',
    messagingSenderId: '975258799788',
    projectId: 'da-quiz-c9e7f',
    authDomain: 'da-quiz-c9e7f.firebaseapp.com',
    storageBucket: 'da-quiz-c9e7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmd3L5E8pA1c0eCjVuUSM51tagtFbtHU4',
    appId: '1:975258799788:android:b40f00184b67c0aa09d909',
    messagingSenderId: '975258799788',
    projectId: 'da-quiz-c9e7f',
    storageBucket: 'da-quiz-c9e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5PgDJnYEMeTWk2IoiuyYSBaqOEizrDo',
    appId: '1:975258799788:ios:ddfcaad5ec48625609d909',
    messagingSenderId: '975258799788',
    projectId: 'da-quiz-c9e7f',
    storageBucket: 'da-quiz-c9e7f.appspot.com',
    iosBundleId: 'io.acameth.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5PgDJnYEMeTWk2IoiuyYSBaqOEizrDo',
    appId: '1:975258799788:ios:44479d9e4ae46a1609d909',
    messagingSenderId: '975258799788',
    projectId: 'da-quiz-c9e7f',
    storageBucket: 'da-quiz-c9e7f.appspot.com',
    iosBundleId: 'io.acameth.myapp.RunnerTests',
  );
}
